<a href="https://colab.research.google.com/github/Sneha8126/ML-Projects/blob/main/NLP_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/twitter_training.csv' ,header=None)

In [ ]:
df.head(10)

,0,1,2,3
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
5,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
6,2402,Borderlands,Positive,So I spent a few hours making something for fu...
7,2402,Borderlands,Positive,So I spent a couple of hours doing something f...
8,2402,Borderlands,Positive,So I spent a few hours doing something for fun...
9,2402,Borderlands,Positive,So I spent a few hours making something for fu...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74682 entries, 0 to 74681
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       74682 non-null  int64
 1   1       74682 non-null  object
 2   2       74682 non-null  object
 3   3       73996 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.3+ MB

In [ ]:
df.shape

(74682, 4)

In [ ]:
df.describe()

                  0
count  74682.000000
mean    6432.586165
std     3740.427870
min        1.000000
25%     3195.000000
50%     6422.000000
75%     9601.000000
max    13200.000000

In [ ]:
df.isnull().sum()

0      0
1      0
2      0
3    686
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(2700)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.columns

Index([0, 1, 2, 3], dtype='int64')

In [ ]:
df.columns = ["Tweet_ID", "Entity", "Sentiment", "Tweet"]

In [ ]:
df.columns

Index(['Tweet_ID', 'Entity', 'Sentiment', 'Tweet'], dtype='object')

In [ ]:
df.dropna(subset=["Tweet"], inplace=True)

In [ ]:
df['Sentiment'].value_counts()

Sentiment
Negative      21698
Positive      19713
Neutral       17708
Irrelevant    12537
Name: count, dtype: int64

In [ ]:
df['Entity'].value_counts().head(10)

Entity
TomClancysRainbowSix    2328
Verizon                 2319
MaddenNFL               2315
CallOfDuty              2314
Microsoft               2304
WorldOfCraft            2300
NBA2K                   2299
LeagueOfLegends         2296
TomClancysGhostRecon    2291
Facebook                2289
Name: count, dtype: int64

In [ ]:
import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

## Lower case

In [ ]:
def lower_text(text):
    return text.lower()

## HTML Tags

In [ ]:
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub('', text)

## Remove URLs

In [ ]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub('', text)

## Remove Punctuation

In [ ]:
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

## Remove Numbers

In [ ]:
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

## Remove Special Characters

In [ ]:
def remove_special_characters(text):
    return re.sub(r'[^a-zA-Z\s]', '', text)

## Remove Extra Spaces

In [ ]:
def remove_extra_spaces(text):
    return re.sub(r'\s+', ' ', text).strip()

## Remove Stopwords

In [ ]:
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

## Lematization

In [ ]:
lemmatizer = WordNetLemmatizer()

def lemmatize_words(text):
    words = text.split()
    words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(words)

## Remove Emojis

In [ ]:
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"
                           u"\U0001F300-\U0001F5FF"
                           u"\U0001F680-\U0001F6FF"
                           u"\U0001F1E0-\U0001F1FF"
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub('', text)

In [ ]:
df['Tweet'] = df['Tweet'].astype(str)

df['Tweet'] = df['Tweet'].apply(lower_text)
df['Tweet'] = df['Tweet'].apply(remove_html_tags)
df['Tweet'] = df['Tweet'].apply(remove_url)
df['Tweet'] = df['Tweet'].apply(remove_punctuation)
df['Tweet'] = df['Tweet'].apply(remove_numbers)
df['Tweet'] = df['Tweet'].apply(remove_special_characters)
df['Tweet'] = df['Tweet'].apply(remove_emoji)
df['Tweet'] = df['Tweet'].apply(remove_extra_spaces)
df['Tweet'] = df['Tweet'].apply(remove_stopwords)
df['Tweet'] = df['Tweet'].apply(lemmatize_words)

In [ ]:
df[['Tweet']].head()

                          Tweet
0  im getting borderland murder
1            coming border kill
2    im getting borderland kill
3   im coming borderland murder
4  im getting borderland murder

In [ ]:
df['Sentiment'].value_counts()

Sentiment
Negative      21698
Positive      19713
Neutral       17708
Irrelevant    12537
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Sentiment'] = le.fit_transform(df['Sentiment'])

df.head()

   Tweet_ID       Entity  Sentiment                         Tweet
0      2401  Borderlands          3  im getting borderland murder
1      2401  Borderlands          3            coming border kill
2      2401  Borderlands          3    im getting borderland kill
3      2401  Borderlands          3   im coming borderland murder
4      2401  Borderlands          3  im getting borderland murder

* 'Irrelevant':0,
* 'Negative':1,
* 'Neutral':2,
* 'Positive':3

In [ ]:
X = df['Tweet']
y = df['Sentiment']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(X)

In [ ]:
X.shape

(71656, 5000)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

Accuracy: 0.6814819983254257
              precision    recall  f1-score   support

           0       0.69      0.54      0.60      2507
           1       0.72      0.78      0.75      4340
           2       0.63      0.64      0.63      3542
           3       0.69      0.71      0.70      3943

    accuracy                           0.68     14332
   macro avg       0.68      0.66      0.67     14332
weighted avg       0.68      0.68      0.68     14332

[[1348  373  360  426]
 [ 161 3374  456  349]
 [ 233  550 2256  503]
 [ 221  402  531 2789]]

## Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

In [ ]:
print("Accuracy:", accuracy_score(y_test, rf_pred))

print(classification_report(y_test, rf_pred))

print(confusion_matrix(y_test, rf_pred))

Accuracy: 0.8762908177504884
              precision    recall  f1-score   support

           0       0.93      0.80      0.86      2507
           1       0.90      0.90      0.90      4340
           2       0.89      0.86      0.87      3542
           3       0.82      0.91      0.86      3943

    accuracy                           0.88     14332
   macro avg       0.88      0.87      0.87     14332
weighted avg       0.88      0.88      0.88     14332

[[2005  125  124  253]
 [  43 3924  116  257]
 [  39  185 3030  288]
 [  61  135  147 3600]]

### Building a Predictive System

In [ ]:
# Function to predict sentiment

def predict_sentiment(input_text):

    # Convert text into TF-IDF features
    input_data = tfidf.transform([input_text])

    # Predict sentiment
    prediction = lr.predict(input_data)

    # Convert numeric label back to original label
    predicted_sentiment = le.inverse_transform(prediction)

    print("Tweet:", input_text)
    print("Prediction:", prediction[0])

    if predicted_sentiment[0] == "Positive":
        print("Sentiment: Positive Tweet 😊")

    elif predicted_sentiment[0] == "Negative":
        print("Sentiment: Negative Tweet 😞")

    elif predicted_sentiment[0] == "Neutral":
        print("Sentiment: Neutral Tweet 😐")

    else:
        print("Sentiment: Irrelevant Tweet 🤷")

In [ ]:
predict_sentiment("I absolutely love this game. The graphics are amazing!")

Tweet: I absolutely love this game. The graphics are amazing!
Prediction: 3
Sentiment: Positive Tweet 😊

In [ ]:
predict_sentiment("This update completely ruined the game.")

Tweet: This update completely ruined the game.
Prediction: 1
Sentiment: Negative Tweet 😞

In [ ]:
predict_sentiment("Microsoft announced a new update today.")

Tweet: Microsoft announced a new update today.
Prediction: 2
Sentiment: Neutral Tweet 😐

In [ ]:
predict_sentiment("I am going to Delhi tomorrow.")

Tweet: I am going to Delhi tomorrow.
Prediction: 3
Sentiment: Positive Tweet 😊

In [ ]:
predict_sentiment('I am very happy because I am in Delhi and my luggage in China')

Tweet: I am very happy because I am in Delhi and my luggage in China
Prediction: 2
Sentiment: Neutral Tweet 😐