<a href="https://colab.research.google.com/github/Sneha8126/ML-Projects/blob/main/Pandas_Sneha.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels=['a','b','c']
my_list = [1,2,3]

In [5]:
pd.Series(my_list)

0    1
1    2
2    3
dtype: int64

In [4]:
pd.Series(my_list,index=labels)

a    1
b    2
c    3
dtype: int64