<a href="https://colab.research.google.com/github/Sneha8126/ML-Projects/blob/main/Spam_Mail_Prediction(Logistic_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Spam Mail Prediction

**Import Dependancy**

In [ ]:
# Import Dependancy
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer

**Import the mail data**

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Toppers Acadmy Data/data/Machine Learning/Chapter 5:- Natural language processing(NLP)/Project/Copy of mail_data.csv')

In [ ]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
df['Category'] = np.where(df['Category'] == 'ham',1,0)

In [ ]:
df['Category'].value_counts()

Category
1    4825
0     747
Name: count, dtype: int64

### Train Test Split

**Sepret data as x and y**

In [ ]:
x = df['Message']
y = df['Category']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=3)

### Feature Extraction

**convert text data into numerical data**

In [ ]:
x[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [ ]:
feature_extraction = TfidfVectorizer(min_df=1, stop_words='english', lowercase=True)

In [ ]:
x_train = feature_extraction.fit_transform(x_train)
x_test = feature_extraction.transform(x_test)

In [ ]:
print(x_train[0])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5 stored elements and shape (1, 7431)>
  Coords	Values
  (0, 2329)	0.38783870336935383
  (0, 3811)	0.34780165336891333
  (0, 2224)	0.413103377943378
  (0, 4456)	0.4168658090846482
  (0, 5413)	0.6198254967574347

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train, y_train)

LogisticRegression()

In [ ]:
train_pred = model.predict(x_train)
train_acc = accuracy_score(y_train, train_pred)
print(train_acc)

0.9676912721561588

In [ ]:
test_pred = model.predict(x_test)
test_acc = accuracy_score(y_test, test_pred)
print(test_acc)

0.9668161434977578

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [ ]:
print(confusion_matrix(y_train, train_pred))

[[ 452  140]
 [   4 3861]]

In [ ]:
print(confusion_matrix(y_test, test_pred))

[[118  37]
 [  0 960]]

### Building a Predictive System

In [ ]:
input_data = ["i am going to delhi."]


input_data = feature_extraction.transform(input_data)

prediction = model.predict(input_data)
print(prediction)

if (prediction[0]==1):
  print('Ham mail')

else:
  print('Spam mail')

[1]
Ham mail